name: api-gateway

on:
  push:
    branches: [develop, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables based on branch
        shell: bash
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "HOST=${{ secrets.GCP_VM_HOST_PROD }}" >> $GITHUB_ENV

            if [ -n "${{ secrets.SERVER_PORT_PROD }}" ]; then
              echo "SERVER_PORT=${{ secrets.SERVER_PORT_PROD }}" >> $GITHUB_ENV
            else
              echo "SERVER_PORT=8000" >> $GITHUB_ENV
            fi

            echo "EUREKA_HOSTNAME=${{ secrets.EUREKA_HOSTNAME_PROD }}" >> $GITHUB_ENV
            echo "EUREKA_PORT=${{ secrets.EUREKA_PORT_PROD }}" >> $GITHUB_ENV

            echo "CORS_HOST=${{ secrets.CORS_HOST_PROD }}" >> $GITHUB_ENV
            echo "CORS_PORT=${{ secrets.CORS_PORT_PROD }}" >> $GITHUB_ENV

            echo "SECOND_CORS_HOST=${{ secrets.SECOND_CORS_HOST_PROD }}" >> $GITHUB_ENV

            echo "PUBLIC_HOST=${{ secrets.PUBLIC_HOST_PROD }}" >> $GITHUB_ENV

          else
            echo "HOST=${{ secrets.GCP_VM_HOST }}" >> $GITHUB_ENV

            if [ -n "${{ secrets.SERVER_PORT }}" ]; then
              echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> $GITHUB_ENV
            else
              echo "SERVER_PORT=8000" >> $GITHUB_ENV
            fi

            echo "EUREKA_HOSTNAME=${{ secrets.EUREKA_HOSTNAME }}" >> $GITHUB_ENV
            echo "EUREKA_PORT=${{ secrets.EUREKA_PORT }}" >> $GITHUB_ENV

            echo "CORS_HOST=${{ secrets.CORS_HOST }}" >> $GITHUB_ENV
            echo "CORS_PORT=${{ secrets.CORS_PORT }}" >> $GITHUB_ENV

            echo "SECOND_CORS_HOST=${{ secrets.SECOND_CORS_HOST }}" >> $GITHUB_ENV

            echo "PUBLIC_HOST=${{ secrets.PUBLIC_HOST }}" >> $GITHUB_ENV
          fi

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@"$HOST" << EOF
            set -e
            cd ./healntrack-api-gateway
            git checkout ${GITHUB_REF_NAME}
            git pull

            sudo docker container prune -f || true
            sudo docker image prune -af || true
            sudo docker builder prune -af || true
            sudo docker volume prune -f || true
            
            sudo docker build -t api-gateway .

            sudo docker stop api-gateway || true
            sudo docker rm api-gateway || true

            sudo docker run -d --name api-gateway \
              -p "$SERVER_PORT:$SERVER_PORT" \
              -e PORT="$SERVER_PORT" \
              -e SERVER_PORT="$SERVER_PORT" \
              -e EUREKA_HOSTNAME="$EUREKA_HOSTNAME" \
              -e EUREKA_PORT="$EUREKA_PORT" \
              -e CORS_HOST="$CORS_HOST" \
              -e CORS_PORT="$CORS_PORT" \
              -e SECOND_CORS_HOST="$SECOND_CORS_HOST" \
              -e PUBLIC_HOST="$PUBLIC_HOST" \
              api-gateway
          EOF
